// Purpose: Monitors the pasteboard, stores bounded clipboard history, and manages image persistence.

import AppKit
import Combine
import CryptoKit
import Foundation
import ImageIO
import os.log
import UniformTypeIdentifiers

@MainActor
final class ClipboardHistoryStore: ObservableObject {
    @Published private(set) var items: [ClipboardItem] = []
    @Published private(set) var lastError: String?

    private let pasteboard: NSPasteboard
    private let storageURL: URL?
    private let imageDirectoryURL: URL?
    private let maxItemCount: Int
    private let retentionInterval: TimeInterval
    private var timer: Timer?
    private var lastChangeCount: Int
    private static let maxTextByteCount = 100_000
    private static let maxImageDataByteCount = 50_000_000
    static let maxImagePixelCount = 16_000_000

    init(
        pasteboard: NSPasteboard = .general,
        storageURL: URL? = ClipboardHistoryStore.defaultStorageURL,
        maxItemCount: Int = 50,
        retentionInterval: TimeInterval = 24 * 60 * 60
    ) {
        self.pasteboard = pasteboard
        self.storageURL = storageURL
        self.imageDirectoryURL = storageURL?
            .deletingLastPathComponent()
            .appendingPathComponent("ClipboardImages", isDirectory: true)
        self.maxItemCount = max(1, maxItemCount)
        self.retentionInterval = max(0, retentionInterval)
        self.lastChangeCount = pasteboard.changeCount
        load()
        pruneHistory()
    }

    deinit {
        timer?.invalidate()
    }

    func startMonitoring() {
        guard timer == nil else { return }
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            guard let store = self else { return }
            // The timer is on the main run loop, so poll in place rather than scheduling
            // a task on every tick for the life of the app.
            MainActor.assumeIsolated {
                store.pollPasteboard()
            }
        }
        RunLoop.main.add(timer!, forMode: .common)
    }

    func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    func clearError() {
        lastError = nil
    }

    func pollPasteboard(now: Date = Date()) {
        if !Thread.isMainThread {
            DispatchQueue.main.async { [weak self] in
                self?.pollPasteboard(now: now)
            }
            return
        }

        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        // Password managers mark what they copy so clipboard managers keep nothing.
        if let types = pasteboard.types, types.contains(where: Self.privateContentTypes.contains) {
            return
        }

        let sourceApplicationName = currentSourceApplicationName()
        if let filePaths = filePathsFromPasteboard() {
            addText(filePaths, sourceApplicationName: sourceApplicationName, at: now)
        } else if let imageData = imageDataFromPasteboard() {
            addImageData(imageData, sourceApplicationName: sourceApplicationName, at: now)
        } else if let text = pasteboard.string(forType: .string) {
            addText(text, sourceApplicationName: sourceApplicationName, at: now)
        } else {
            pruneHistory(now: now)
        }
    }

    /// Markers from nspasteboard.org that password managers and similar tools set to
    /// ask clipboard managers not to record an entry.
    static let privateContentTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    /// Copying files puts file URLs on the pasteboard together with image
    /// representations of their icons. Record the paths rather than an icon picture.
    private func filePathsFromPasteboard() -> String? {
        guard pasteboard.types?.contains(.fileURL) == true,
              let urls = pasteboard.readObjects(
                forClasses: [NSURL.self],
                options: [.urlReadingFileURLsOnly: true]
              ) as? [URL],
              !urls.isEmpty else {
            return nil
        }

        return urls.map(\.path).joined(separator: "\n")
    }

    func addText(_ text: String, sourceApplicationName: String? = nil, at date: Date = Date()) {
        let normalized = text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty else { return }
        // History preserves exact clipboard text, so enforce the byte limit on the stored payload,
        // including whitespace and multi-byte characters.
        guard text.utf8.count <= Self.maxTextByteCount else {
            lastError = "Clipboard text too large (max 100KB)"
            return
        }

        items.removeAll { !$0.isImage && $0.text == text }
        items.insert(ClipboardItem(text: text, sourceApplicationName: sourceApplicationName, createdAt: date), at: 0)
        pruneHistory(now: date)
        save()
    }

    @discardableResult
    func addImageData(_ imageData: Data, sourceApplicationName: String? = nil, at date: Date = Date()) -> Bool {
        guard !imageData.isEmpty else { return false }
        guard imageData.count <= Self.maxImageDataByteCount else {
            lastError = "Image too large (max 50MB)"
            return false
        }

        guard let pixelCount = Self.imagePixelCount(forImageData: imageData) else {
            lastError = "Could not read image dimensions."
            return false
        }
        guard pixelCount <= Self.maxImagePixelCount else {
            lastError = "Image too large (max 16MP)"
            return false
        }

        let id = UUID()

        // Always persist to disk — never hold large image Data inline in the items array.
        // Retry once on failure for transient I/O issues.
        var fileName = storeImageData(imageData, id: id)
        if fileName == nil {
            fileName = storeImageData(imageData, id: id)
        }

        guard let fileName else {
            lastError = "Failed to store clipboard image to disk."
            return false
        }

        // Compute fingerprint once and pass it through so removeImageItemsMatching
        // doesn't re-hash the same Data.
        let fingerprint = Self.imageFingerprint(for: imageData)

        // Only dedup after the disk write succeeds — otherwise we'd delete
        // existing items and then fail to add the replacement, losing data.
        removeImageItemsMatching(imageData, knownFingerprint: fingerprint)

        items.insert(
            ClipboardItem(
                id: id,
                text: "Image",
                imageData: nil,
                imageFileName: fileName,
                imageFingerprint: fingerprint,
                sourceApplicationName: sourceApplicationName,
                createdAt: date
            ),
            at: 0
        )
        pruneHistory(now: date)
        save()
        compactStoredImageIfNeeded(itemID: id, fileName: fileName, imageData: imageData)
        return true
    }

    /// TIFF usually arrives uncompressed, about 48MB for a 12MP photo, and was stored
    /// byte for byte. Rewrite it as PNG off the main thread once the entry is listed.
    /// The fingerprint stays that of the data as it arrived, so copying the same image
    /// again is still recognised as a duplicate.
    private func compactStoredImageIfNeeded(itemID: UUID, fileName: String, imageData: Data) {
        guard let imageDirectoryURL,
              Self.imageTypeIdentifier(for: imageData) == UTType.tiff.identifier else {
            return
        }

        let sourceURL = imageDirectoryURL.appendingPathComponent(fileName)
        let compactFileName = "\(itemID.uuidString).png"
        let compactURL = imageDirectoryURL.appendingPathComponent(compactFileName)

        Task.detached(priority: .utility) { [weak self] in
            guard let pngData = Self.pngData(fromImageAt: sourceURL),
                  (try? pngData.write(to: compactURL, options: .atomic)) != nil else {
                return
            }

            await self?.finishCompaction(
                itemID: itemID,
                originalFileName: fileName,
                compactFileName: compactFileName
            )
        }
    }

    private func finishCompaction(itemID: UUID, originalFileName: String, compactFileName: String) {
        guard let imageDirectoryURL else { return }
        let compactURL = imageDirectoryURL.appendingPathComponent(compactFileName)

        // Deleted, pruned, or deduplicated while the PNG was being written.
        guard let index = items.firstIndex(where: { $0.id == itemID && $0.imageFileName == originalFileName }) else {
            try? FileManager.default.removeItem(at: compactURL)
            return
        }

        items[index].imageFileName = compactFileName
        save()
        try? FileManager.default.removeItem(at: imageDirectoryURL.appendingPathComponent(originalFileName))
    }

    nonisolated private static func pngData(fromImageAt url: URL) -> Data? {
        autoreleasepool {
            guard let source = CGImageSourceCreateWithURL(url as CFURL, nil),
                  let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else {
                return nil
            }

            let data = NSMutableData()
            guard let destination = CGImageDestinationCreateWithData(
                data,
                UTType.png.identifier as CFString,
                1,
                nil
            ) else {
                return nil
            }
            CGImageDestinationAddImage(destination, image, nil)
            return CGImageDestinationFinalize(destination) ? data as Data : nil
        }
    }

    func delete(_ item: ClipboardItem) {
        clearPasteboardIfCurrentItem(item)
        items.removeAll { $0.id == item.id }
        deleteImageFile(for: item)
        save()
    }

    func imageData(for item: ClipboardItem) -> Data? {
        if let imageData = item.imageData {
            return imageData
        }

        guard let imageFileName = item.imageFileName,
              let imageDirectoryURL else {
            return nil
        }

        return try? Data(contentsOf: imageDirectoryURL.appendingPathComponent(imageFileName))
    }

    func imageURL(for item: ClipboardItem) -> URL? {
        guard let imageFileName = item.imageFileName,
              let imageDirectoryURL else {
            return nil
        }

        return imageDirectoryURL.appendingPathComponent(imageFileName)
    }

    @discardableResult
    func copyToPasteboard(_ item: ClipboardItem) -> Bool {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return false }
        let itemToCopy = items[index]

        if itemToCopy.isImage {
            if let imageData = imageData(for: itemToCopy) {
                setPasteboardImageData(imageData)
                return true
            }
            return false
        }

        let normalized = itemToCopy.text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty else { return false }

        setPasteboardText(itemToCopy.text)
        return true
    }

    func copyToPasteboardAndPromote(_ item: ClipboardItem) {
        guard copyToPasteboard(item) else { return }
        promoteItem(item)
    }

    func promoteItem(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else { return }
        var promotedItem = items.remove(at: index)
        let now = Date()

        if promotedItem.isImage {
            promotedItem.updatedAt = now
            if let promotedImageData = imageData(for: promotedItem) {
                removeImageItemsMatching(promotedImageData)
            }
            items.insert(promotedItem, at: 0)
            save()
            return
        }

        let normalized = promotedItem.text.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !normalized.isEmpty else {
            save()
            return
        }

        promotedItem.createdAt = now
        promotedItem.updatedAt = now
        items.removeAll { !$0.isImage && $0.text == promotedItem.text }
        items.insert(promotedItem, at: 0)
        save()
    }

    func setPasteboardText(_ text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
        lastChangeCount = pasteboard.changeCount
    }

    func setPasteboardImageData(_ imageData: Data) {
        pasteboard.clearContents()
        pasteboard.setData(imageData, forType: Self.pasteboardType(forImageData: imageData))
        lastChangeCount = pasteboard.changeCount
    }

    func pruneHistory(now: Date = Date()) {
        let cutoff = now.addingTimeInterval(-retentionInterval)
        var retainedItems = items.filter { $0.createdAt >= cutoff }
        if retainedItems.count > maxItemCount {
            retainedItems = Array(retainedItems.prefix(maxItemCount))
        }

        guard retainedItems.map(\.id) != items.map(\.id) else { return }

        let retainedIDs = Set(retainedItems.map(\.id))
        let removedItems = items.filter { !retainedIDs.contains($0.id) }
        items = retainedItems
        deleteImageFiles(for: removedItems)
        save()
    }

    private func load() {
        guard let storageURL, FileManager.default.fileExists(atPath: storageURL.path) else { return }

        let records: [LossyClipboardItem]
        do {
            let data = try Data(contentsOf: storageURL)
            records = try JSONDecoder().decode([LossyClipboardItem].self, from: data)
        } catch {
            // Nothing readable at all. Keep the file rather than letting the next save
            // overwrite it.
            preserveUnreadableHistory(reason: error.localizedDescription)
            items = []
            return
        }

        let decoded = records.compactMap(\.item)
        let unreadableCount = records.count - decoded.count
        if unreadableCount > 0 {
            preserveUnreadableHistory(
                reason: "\(unreadableCount) \(unreadableCount == 1 ? "entry" : "entries") could not be read"
            )
        }

        items = decoded.sorted { $0.createdAt > $1.createdAt }
        migrateLegacyImageDataToFilesIfNeeded()
    }

    /// Copies the history file aside before anything can overwrite it, so a format
    /// change or a damaged record costs a notice instead of every entry.
    private func preserveUnreadableHistory(reason: String) {
        guard let storageURL else { return }

        let backupURL = storageURL
            .deletingPathExtension()
            .appendingPathExtension("unreadable-\(Int(Date().timeIntervalSince1970)).json")
        try? FileManager.default.copyItem(at: storageURL, to: backupURL)

        lastError = "Some clipboard history could not be read (\(reason)). The original file was kept as \(backupURL.lastPathComponent)."
        os_log("Clipboard history partly unreadable: %{public}@", log: .default, type: .error, reason)
    }

    private func save() {
        guard let storageURL else { return }

        do {
            try FileManager.default.createDirectory(
                at: storageURL.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
            let data = try JSONEncoder().encode(items)
            try data.write(to: storageURL, options: .atomic)
            lastError = nil
        } catch {
            lastError = "Failed to save clipboard history: \(error.localizedDescription)"
            os_log("Failed to save clipboard history: %{public}@", log: .default, type: .error, error.localizedDescription)
        }
    }

    private nonisolated static var defaultStorageURL: URL? {
        guard let supportDirectory = FileManager.default
            .urls(for: .applicationSupportDirectory, in: .userDomainMask)
            .first else {
            return nil
        }

        let directory = supportDirectory.appendingPathComponent("Space", isDirectory: true)
        migrateLegacyStorage(
            from: supportDirectory.appendingPathComponent("Squirrel", isDirectory: true),
            to: directory
        )
        return directory.appendingPathComponent("clipboard-history.json")
    }

    // The app was called Squirrel before it was renamed; carry that history over once.
    private nonisolated static func migrateLegacyStorage(from legacyDirectory: URL, to directory: URL) {
        let fileManager = FileManager.default
        guard fileManager.fileExists(atPath: legacyDirectory.path),
              !fileManager.fileExists(atPath: directory.path) else {
            return
        }

        try? fileManager.moveItem(at: legacyDirectory, to: directory)
    }

    private func storeImageData(_ imageData: Data, id: UUID) -> String? {
        guard let imageDirectoryURL else { return nil }

        do {
            try FileManager.default.createDirectory(at: imageDirectoryURL, withIntermediateDirectories: true)
            let fileName = "\(id.uuidString).image"
            try imageData.write(to: imageDirectoryURL.appendingPathComponent(fileName), options: .atomic)
            return fileName
        } catch {
            lastError = "Failed to store clipboard image: \(error.localizedDescription)"
            os_log("Failed to store clipboard image: %{public}@", log: .default, type: .error, error.localizedDescription)
            return nil
        }
    }

    private func removeImageItemsMatching(_ imageData: Data, knownFingerprint: String? = nil) {
        let fingerprint = knownFingerprint ?? Self.imageFingerprint(for: imageData)
        let duplicates = items.filter { item in
            guard item.isImage else { return false }
            if item.imageFingerprint == fingerprint {
                return true
            }
            guard item.imageFingerprint == nil else { return false }
            return self.imageData(for: item) == imageData
        }
        guard !duplicates.isEmpty else { return }

        let duplicateIDs = Set(duplicates.map(\.id))
        items.removeAll { duplicateIDs.contains($0.id) }
        deleteImageFiles(for: duplicates)
    }

    private func migrateLegacyImageDataToFilesIfNeeded() {
        guard imageDirectoryURL != nil else { return }

        var didMigrate = false
        for index in items.indices {
            if let imageData = items[index].imageData {
                if items[index].imageFingerprint == nil {
                    items[index].imageFingerprint = Self.imageFingerprint(for: imageData)
                    didMigrate = true
                }

                if items[index].imageFileName == nil,
                   let fileName = storeImageData(imageData, id: items[index].id) {
                    items[index].imageData = nil
                    items[index].imageFileName = fileName
                    didMigrate = true
                }
            } else if items[index].isImage,
                      items[index].imageFingerprint == nil,
                      let imageData = imageData(for: items[index]) {
                items[index].imageFingerprint = Self.imageFingerprint(for: imageData)
                didMigrate = true
            }
        }

        if didMigrate {
            save()
        }
    }

    private func deleteImageFiles(for items: [ClipboardItem]) {
        for item in items {
            deleteImageFile(for: item)
        }
    }

    private func deleteImageFile(for item: ClipboardItem) {
        guard let imageDirectoryURL,
              let imageFileName = item.imageFileName else {
            return
        }

        try? FileManager.default.removeItem(at: imageDirectoryURL.appendingPathComponent(imageFileName))
    }

    /// Image representations to take from the pasteboard, most compact first. TIFF,
    /// which apps usually provide uncompressed (about 96MB for a 24MP photo), comes last.
    /// macOS only ever translates other image types to TIFF, never the other way, so
    /// asking for these in order never forces a lossy conversion.
    static let imagePasteboardTypes: [NSPasteboard.PasteboardType] = [
        .png,
        NSPasteboard.PasteboardType(UTType.jpeg.identifier),
        NSPasteboard.PasteboardType(UTType.heic.identifier),
        .tiff
    ]

    /// The first image representation the pasteboard holds, without rasterising.
    private func encodedImageDataOnPasteboard() -> Data? {
        for type in Self.imagePasteboardTypes {
            if let data = pasteboard.data(forType: type), !data.isEmpty {
                return data
            }
        }
        return nil
    }

    private func imageDataFromPasteboard() -> Data? {
        if let data = encodedImageDataOnPasteboard() {
            return data
        }

        // Fallback: anything else NSImage can read, such as a PDF, rendered to TIFF.
        guard let image = pasteboard.readObjects(forClasses: [NSImage.self])?.first as? NSImage else {
            return nil
        }

        guard Self.imagePixelCount(for: image) <= Self.maxImagePixelCount else {
            lastError = "Image too large (max 16MP)"
            return nil
        }

        return autoreleasepool {
            image.tiffRepresentation
        }
    }

    /// The pixels `tiffRepresentation` would produce. Vector representations (PDF, EPS)
    /// report no pixel size at all, so they are measured by the point size they render
    /// at: counting them as one pixel let a 200-inch PDF page through to a 791MB bitmap.
    static func imagePixelCount(for image: NSImage) -> Int {
        let renderedCount = pixelCount(width: image.size.width, height: image.size.height)
        let representationCounts = image.representations.map { representation -> Int in
            guard representation.pixelsWide > 0, representation.pixelsHigh > 0 else {
                return renderedCount
            }
            return pixelCount(width: CGFloat(representation.pixelsWide), height: CGFloat(representation.pixelsHigh))
        }
        return representationCounts.max() ?? renderedCount
    }

    /// Width times height, saturating instead of trapping on huge or non-finite sizes.
    private static func pixelCount(width: CGFloat, height: CGFloat) -> Int {
        guard width.isFinite, height.isFinite else { return Int.max }
        let product = Double(max(width, 1)) * Double(max(height, 1))
        return product >= Double(Int.max) ? Int.max : Int(product)
    }

    private static func imagePixelCount(forImageData imageData: Data) -> Int? {
        guard let source = CGImageSourceCreateWithData(imageData as CFData, [
            kCGImageSourceShouldCache: false
        ] as CFDictionary),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, [
                kCGImageSourceShouldCache: false
              ] as CFDictionary) as? [CFString: Any] else {
            return nil
        }

        guard let width = (properties[kCGImagePropertyPixelWidth] as? NSNumber)?.intValue,
              let height = (properties[kCGImagePropertyPixelHeight] as? NSNumber)?.intValue else {
            return nil
        }
        return max(width, 1) * max(height, 1)
    }

    private static func imageFingerprint(for imageData: Data) -> String {
        SHA256.hash(data: imageData)
            .map { String(format: "%02x", $0) }
            .joined()
    }

    /// Declares what the stored data really is (PNG, JPEG, HEIC or TIFF). For anything
    /// but TIFF the system also offers a TIFF translation to apps that only read TIFF.
    private static func pasteboardType(forImageData imageData: Data) -> NSPasteboard.PasteboardType {
        imageTypeIdentifier(for: imageData).map { NSPasteboard.PasteboardType($0) } ?? .tiff
    }

    private static func imageTypeIdentifier(for imageData: Data) -> String? {
        guard let source = CGImageSourceCreateWithData(imageData as CFData, nil) else { return nil }
        return CGImageSourceGetType(source) as String?
    }

    private func currentSourceApplicationName() -> String? {
        guard let application = NSWorkspace.shared.frontmostApplication else { return nil }
        guard application.bundleIdentifier != Bundle.main.bundleIdentifier else { return nil }
        return application.localizedName
    }

    private func clearPasteboardIfCurrentItem(_ item: ClipboardItem) {
        if itemMatchesPasteboard(item) {
            pasteboard.clearContents()
            lastChangeCount = pasteboard.changeCount
        }
    }

    private func itemMatchesPasteboard(_ item: ClipboardItem) -> Bool {
        if item.isImage {
            // Never the rasterising fallback: that could render a vector image at
            // hundreds of megabytes just to answer this.
            guard let pasteboardData = encodedImageDataOnPasteboard() else { return false }

            // The fingerprint is of the data as it arrived, which still matches after a
            // TIFF entry has been compacted to PNG on disk.
            if let fingerprint = item.imageFingerprint, Self.imageFingerprint(for: pasteboardData) == fingerprint {
                return true
            }
            return imageData(for: item) == pasteboardData
        }

        return pasteboard.string(forType: .string) == item.text
    }
}

/// Decodes one history entry, or nothing if it cannot be read, so that a single bad
/// record does not fail the whole array.
private struct LossyClipboardItem: Decodable {
    let item: ClipboardItem?

    init(from decoder: Decoder) throws {
        item = try? ClipboardItem(from: decoder)
    }
}
